name: local-db

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=matheus
      - POSTGRES_PASSWORD=matheus
      - POSTGRES_DB=localdatabase